import streamlit as st
import json
import pandas as pd

# Set up and run this Streamlit App
from logics.customer_query_handler import process_user_message

# region <--------- Streamlit App Configuration --------->
st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)
# endregion <--------- Streamlit App Configuration --------->

# Sidebar for navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", ["Home", "About Us", "View All Courses"])

if page == "Home":
    st.title("Streamlit App")

    form = st.form(key="form")
    form.subheader("Prompt")

    user_prompt = form.text_area("Enter your prompt here", height=200)

    if form.form_submit_button("Submit"):
        st.toast(f"User Input Submitted - {user_prompt}")
        response, course_details = process_user_message(user_prompt)  # Unpack both response and course details
    
        st.write(response)
    
        # Display course details if available
        if course_details:
            st.subheader("Relevant Course Details:")
            for course_detail in course_details:
                st.write(f"**Course Name**: {course_detail['name']}")
                st.write(f"**Description**: {course_detail['description']}")
                st.write(f"**Rating**: {course_detail['rating']}")
                st.write(f"**Price**: {course_detail['price']}")
                st.write(f"**Skills Covered**: {', '.join(course_detail['skills_covered'])}")
                st.write("---")
        else:
            st.write("No relevant courses found.")
        
        print(f"User Input is {user_prompt}")

elif page == "About Us":
    st.title("About Us")
    
    st.write("""
        Welcome to My Streamlit App! This app is designed to help you with various tasks.
        
        ### How to use this App
        You can enter your queries in the prompt section on the home page. 
        Once you submit your query, our system will process it and return a relevant response.
        
        Feel free to explore and make the most out of this application!
    """)

    # Expander for additional information
    with st.expander("How to use this App", expanded=False):
        st.write("""
            1. Navigate to the Home page using the sidebar.
            2. Enter your prompt in the text area provided.
            3. Click on 'Submit' to send your query.
            4. Review the response generated by the app.
            5. Use the sidebar to return to this About Us section or back to Home.
        """)

elif page == "View All Courses":
    st.title("View All Courses")
    
    # Load courses from JSON file
    with open('./data/courses-full.json', 'r') as file:
        courses = json.load(file)

    # Convert courses data into a DataFrame for better display
    courses_df = pd.DataFrame(courses)

    # Display the courses in a table format
    if not courses_df.empty:
        st.dataframe(courses_df)
    else:
        st.write("No courses available.")
